# Generated by Django 4.1.3 on 2022-12-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ostatok',
            field=models.IntegerField(default=2400),
        ),
    ]
