# Generated by Django 4.1.3 on 2022-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_novosti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novosti',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='novosti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='novosti',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
