# Generated by Django 4.1.3 on 2022-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_novosti_date_time_alter_novosti_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novosti',
            name='image',
        ),
        migrations.AddField(
            model_name='novosti',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 5'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 9'),
        ),
        migrations.AddField(
            model_name='novosti',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='novost_file', verbose_name='Фото 10'),
        ),
    ]
