# Generated by Django 4.1.3 on 2022-12-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dohods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rashods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата публикации: ')),
                ('rashod', models.CharField(max_length=300, verbose_name='Расход: ')),
                ('summr', models.IntegerField(verbose_name='Сумма: ')),
            ],
        ),
    ]
