# Generated by Django 4.1.3 on 2022-12-18 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_people_article_date_alter_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст')),
                ('files', models.FileField(upload_to='', verbose_name='Документ')),
                ('boolens', models.BooleanField(default=True, verbose_name='Видимость ')),
            ],
            options={
                'verbose_name': 'Документы ',
                'verbose_name_plural': 'Документы ',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Общий фонд', 'verbose_name_plural': 'Общий фонд '},
        ),
        migrations.AlterModelOptions(
            name='dohods',
            options={'verbose_name': 'Доходы ', 'verbose_name_plural': 'Доходы '},
        ),
        migrations.AlterModelOptions(
            name='novosti',
            options={'verbose_name': 'Новости ', 'verbose_name_plural': 'Новости '},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Члены фонда  ', 'verbose_name_plural': 'Члены фонда (ФИО)  '},
        ),
        migrations.AlterModelOptions(
            name='rashods',
            options={'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы '},
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 18, 22, 11, 46, 166760), verbose_name='Дата '),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people', verbose_name='ФИО '),
        ),
        migrations.AlterField(
            model_name='article',
            name='ostatok',
            field=models.IntegerField(default=2400, verbose_name='Остаток '),
        ),
        migrations.AlterField(
            model_name='article',
            name='sdal',
            field=models.IntegerField(verbose_name='Сдал '),
        ),
        migrations.AlterField(
            model_name='dohods',
            name='date',
            field=models.DateField(verbose_name='Дата публикации '),
        ),
        migrations.AlterField(
            model_name='dohods',
            name='otkogo',
            field=models.CharField(max_length=300, verbose_name='От кого '),
        ),
        migrations.AlterField(
            model_name='dohods',
            name='summa',
            field=models.IntegerField(verbose_name='Сумма '),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=120, verbose_name='ФИО '),
        ),
    ]
