# Generated by Django 4.1.3 on 2022-12-18 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_document_alter_article_options_alter_dohods_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 18, 22, 21, 0, 973779), verbose_name='Дата '),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_time',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
